# Configuración específica para la estrategia cross_ema

exchange:
  name: binance
  symbol: BTC/USDT
  timeframe: 1m
  start_date: 2025-06-01
  end_date: 2025-06-12

allowed_symbols:
  - BTC/USDT
  - ETH/USDT

strategy:
  type: ema_cross
  params:
    fast: 12
    slow: 26
    limit: 100

risk:
  max_position_size: 0.01   # 1% del balance
  stop_loss_pct: 0.02       # 2%
